### ISSUE TITLE
`analyze CalculatorService.csproj` `No such command`

### ISSUE THREAD

**Issue by Shereef** [dotnet/upgrade-assistant#1523] opened 2023-09-29 13:19 UTC
https://github.com/dotnet/upgrade-assistant#analyze-path

```
$ dotnet tool update -g --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources upgrade-assistant
Tool 'upgrade-assistant' was reinstalled with the latest stable version (version '0.5.261').

$ upgrade-assistant.exe --version
0.5.261.51392

$ upgrade-assistant.exe
USAGE:
    upgrade-assistant [OPTIONS] <COMMAND>

EXAMPLES:
    upgrade-assistant upgrade <PROJECT_PATH>
    upgrade-assistant upgrade <PROJECT_PATH> --operation Inplace --targetFramework net6.0
    upgrade-assistant upgrade <PROJECT_PATH> --operation SideBySide --targetFramework LTS --destination <NEW_PROJECT_NAME_OR_PATH>

OPTIONS:
    -h, --help       Prints help information
    -v, --version    Prints version information

COMMANDS:
    upgrade    Upgrade project or its features. This command lets you pick upgrade options and guides through upgrade process

$ upgrade-assistant analyze CalculatorService.csproj

Error: Unknown command 'analyze'.

       analyze CalculatorService.csproj
       ^^^^^^^ No such command
```

**Comment by jstedfast** [comment] 2023-09-29 15:28
duplicate of issue #1491

**Closed by jstedfast** 2023-09-29 15:28 UTC
Labels: duplicate
