### ISSUE TITLE
Package analysis failed

### ISSUE THREAD

**Issue by ryanliang88** [dotnet/upgrade-assistant#836] opened 2021-08-30 21:42 UTC
- [ ] Include the log file `upgrade-assistant.clef` that is produced in the working directory

### Describe the bug

> FTL] Package analysis failed (analyzer Target compatibility reference analyzer: Collection was modified; enumeration operation may not execute.

Bug believed to be here
https://github.com/dotnet/upgrade-assistant/blob/09731053296437986b252866f024ff9e4ce8ee08/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Packages/Analyzers/TargetCompatibilityReferenceAnalyzer.cs#L45
https://github.com/dotnet/upgrade-assistant/blob/09731053296437986b252866f024ff9e4ce8ee08/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Packages/Analyzers/TargetCompatibilityReferenceAnalyzer.cs#L88

### Exceptions (if any)

Likely `System.InvalidOperationException`

### Further technical details
`systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043

`upgrade-assistant --version`
0.2.241603+99dc6c7bf12364ae199f7acd8d0d42c631508de0

`dotnet --list-sdks`
2.2.207 [C:\Program Files\dotnet\sdk]
3.1.101 [C:\Program Files\dotnet\sdk]
3.1.401 [C:\Program Files\dotnet\sdk]
5.0.302 [C:\Program Files\dotnet\sdk]
5.0.400 [C:\Program Files\dotnet\sdk]

**Comment by twsouthwick** [comment] 2021-08-31 17:35
@sunandabalu Can you take a look at this? Looks to be in the analysis feature

**Comment by sunandabalu** [comment] 2021-09-07 22:33
@ryanliang88 Could you attach the log file and / or the csproj you are seeing this issue for?

**Comment by ryanliang88** [comment] 2021-09-08 01:03
Log file has been attached below (with some packages removed for general privacy reasons. Please specify further if needed)
[log.txt](https://github.com/dotnet/upgrade-assistant/files/7125016/log.txt)

**Comment by sunandabalu** [comment] 2021-09-08 21:05
@ryanliang88 I don't see the `System.InvalidOperationException` in the log that you have attached, was it one of the package mentions you cleaned up for privacy reasons?

**Comment by ryanliang88** [comment] 2021-09-08 23:56
The exception I specified isn't in the logs and was not ever logged. I suspected it may be that because the error that's in the log is the following line 260:

2021-09-01 15:29:28.013 -07:00 [FTL] Package analysis failed (analyzer Target compatibility reference analyzer: Collection was modified; enumeration operation may not execute.

which I believe is usually the `System.InvalidOperationException`

**Comment by ryanliang88** [comment] 2021-09-15 17:16
Any update to this bug?

**Comment by sunandabalu** [comment] 2021-09-15 19:14
@ryanliang88 Is this bug blocking your ability to use UA for upgrade / analyze ? Unfortunately no progress on this yet due to other competing priorities, if this is blocking then we can consider re-prioritizing work on this bug.

**Comment by ryanliang88** [comment] 2021-09-15 19:19
It's not completely blocking, but it's blocking the "Update NuGet Packages" step which I've attempted to migrate manually. I was hoping to have this fixed and confirm that I've migrated correctly but it's fine to leave as is for the meantime. 

Thanks for the update

**Comment by sunandabalu** [comment] 2021-09-15 20:04
> It's not completely blocking, but it's blocking the "Update NuGet Packages" step which I've attempted to migrate manually. I was hoping to have this fixed and confirm that I've migrated correctly but it's fine to leave as is for the meantime.
> 
> Thanks for the update

@ryanliang88 Adding a simple fix to unblock you - https://github.com/dotnet/upgrade-assistant/pull/850

**Comment by ryanliang88** [comment] 2021-09-15 20:08
Lovely, thank you. Do I just wait for PR approval and then rerun the following?:
`dotnet tool install -g upgrade-assistant`

**Comment by sunandabalu** [comment] 2021-09-15 20:30
> Lovely, thank you. Do I just wait for PR approval and then rerun the following?:
> `dotnet tool install -g upgrade-assistant`
> 
> I'm not totally sure how to get this new update (not sure how to build since I tried building locally but lots of things weren't working)

Once the PR is merged, you will need to pick the tool update from the public AzDO feed like `dotnet tool update -g upgrade-assistant --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json`

**Comment by ryanliang88** [comment] 2021-09-15 20:37
I'll give it a shot. Thanks again!

**Comment by ryanliang88** [comment] 2021-09-15 22:37
I ran the following twice and it says that:
`dotnet tool update -g upgrade-assistant --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json`

Tool 'upgrade-assistant' was reinstalled with the latest stable version (version '0.3.246302').

What is the version for the PR that was just completed and how do I get it?

**Closed** 2021-09-15 23:32 UTC
Labels: bug, community reported, Triaged

**Comment by sunandabalu** [comment] 2021-09-15 23:34
> I ran the following twice and it says that:
> `dotnet tool update -g upgrade-assistant --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json`
> 
> Tool 'upgrade-assistant' was reinstalled with the latest stable version (version '0.3.246302').
> 
> What is the version for the PR that was just completed and how do I get it?
> 
> Edit:
> Oh, it seems like the PR is waiting for completion as of this comment

I just merged the PR, we need to wait for the CI to pick the commit and push to the feed. I'll let you know when the process completes.

**Comment by ryanliang88** [comment] 2021-09-15 23:34
Great to hear. Thank you!

**Comment by sunandabalu** [comment] 2021-09-16 01:22
@ryanliang88 The change is pushed to nuget, you can pick the version 0.3.246501 to get the change.

**Comment by ryanliang88** [comment] 2021-09-16 03:26
The bug itself can be considered fully resolved. I'm now unfortunately running into the following issue which is exactly what I had to try to do. Is there anything we can do about this?

https://github.com/dotnet/upgrade-assistant/blob/9814e6485222fc73128b9fdc64633c6a5322b57b/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Packages/PackageUpdaterStep.cs#L142

**Comment by sunandabalu** [comment] 2021-09-16 04:45
> The bug itself can be considered fully resolved. I'm now unfortunately running into the following issue which is exactly what I had to try to do. Is there anything we can do about this?
> 
> https://github.com/dotnet/upgrade-assistant/blob/9814e6485222fc73128b9fdc64633c6a5322b57b/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Packages/PackageUpdaterStep.cs#L142

@mjrousos could you provide some guidance here?

**Comment by mjrousos** [comment] 2021-09-16 15:52
The PackageUpdaterStep runs dependency analyzers repeatedly until it stops finding things that need to be updated. This is done so that if a later analyzer makes a change previous analyzers have an opportunity to react to it. 

Hitting this error is almost certainly a UA bug, but I can't think of why @sunandabalu's recent fix would have triggered it. @ryanliang88, are you able to share the csproj file that is running into this so that we can step through it in a debugger and figure out where the issue is?

**Comment by ryanliang88** [comment] 2021-09-16 17:34
I will get back to you ASAP as it's a potential privacy concern that may require review.

**Comment by SniperED007** [comment] 2021-12-26 21:25
I'm getting the following error as well:

`[21:20:08 INF] Applying upgrade step Clean up NuGet package references
[21:20:08 INF] Adding package reference: Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, Version=0.3.261602
[21:20:14 INF] Reference to .NET Upgrade Assistant analyzer package (Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, version 0.3.261602) needs to be added
[21:20:14 INF] Adding package reference: Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, Version=0.3.261602
[21:20:19 INF] Reference to .NET Upgrade Assistant analyzer package (Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, version 0.3.261602) needs to be added
[21:20:19 INF] Adding package reference: Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, Version=0.3.261602
[21:20:25 INF] Reference to .NET Upgrade Assistant analyzer package (Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, version 0.3.261602) needs to be added
[21:20:25 ERR] Maximum package analysis and update iterations reached. Review NuGet dependencies manually
[21:20:25 WRN] Upgrade step Clean up NuGet package references failed: Failed: Maximum package analysis and update iterations reached`

Is there any way to manually get around this?
