### ISSUE TITLE
upgrade-assistant analyze option is missing 

### ISSUE THREAD

**Issue by jagrut-patel** [dotnet/upgrade-assistant#1497] opened 2023-06-30 21:38 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

upgrade-assistant analyze option is not available.

upgrade-assistant analyze <path to csproj> outputs "Error: Unknown command 'analyze'."

Here is the output of  "upgrade-assistant" help

USAGE:
    upgrade-assistant [OPTIONS] <COMMAND>

EXAMPLES:
    upgrade-assistant upgrade <PROJECT_PATH>
    upgrade-assistant upgrade <PROJECT_PATH> --operation Inplace --targetFramework net6.0
    upgrade-assistant upgrade <PROJECT_PATH> --operation SideBySide --targetFramework LTS --destination <NEW_PROJECT_NAME_OR_PATH>

OPTIONS:
    -h, --help       Prints help information
    -v, --version    Prints version information

COMMANDS:
    upgrade    Upgrade project or its features. This command lets you pick upgrade options and guides through upgrade process

**Comment by tentom** [comment] 2023-07-04 08:02
I have the same problem on Mac.

**Comment by tentom** [comment] 2023-07-04 22:12
A temporary workaround for me is to uninstall and install the previous version.
```
dotnet tool install --global upgrade-assistant --version 0.4.421302
```

**Comment by sjansen-hv** [comment] 2023-08-31 13:26
This is a duplicate of https://github.com/dotnet/upgrade-assistant/issues/1491

**Comment by jstedfast** [comment] 2023-08-31 14:29
There are a lot of duplicates about the analyze command missing in the latest versions.

Starting with v0.5, the analyze command was removed.

Note: technically, it wasn't removed so much as the entire program was rewritten from scratch and the analyze command hasn't been implemented (yet?). In fact, this repo is obsolete and no longer contains the code for the upgrade-assistant tool. It was moved to another repo that gets pulled in by the Visual Studio build for better integration.

**Comment by eduarddejong** [comment] 2023-08-31 16:39
> There are a lot of duplicates about the analyze command missing in the latest versions.
> 
> Starting with v0.5, the analyze command was removed.
> 
> Note: technically, it wasn't removed so much as the entire program was rewritten from scratch and the analyze command hasn't been implemented (yet?). In fact, this repo is obsolete and no longer contains the code for the upgrade-assistant tool. It was moved to another repo that gets pulled in by the Visual Studio build for better integration.

Ah, I looked closer now, and it turns out that Nuget also shows a different project "Project website" for this tool:

https://www.nuget.org/packages/upgrade-assistant/0.4.421302
--> Project website: https://github.com/dotnet/upgrade-assistant

https://www.nuget.org/packages/upgrade-assistant/0.5.261
--> Project website: https://go.microsoft.com/fwlink/?LinkID=2202641

I am not a fan of this kind of practice! I was not even sure that this was actually possible. But turns out it is.

This gives me the impression that Microsoft close sourced (!) this project from now on, and it's really becoming a proprietary Visual Studio-only tool.
That's why I do not like this.

**However** if this is only just a temporary situation, then let's leave it for what it is now.

But I would rather see that the new repository was already available to others before releasing new versions.
In that way others can keep contributing and help development, as it should be with an open source project.

**Comment by jstedfast** [comment] 2023-09-21 11:47
Marking this as a duplicate of issue #1491

**Closed by jstedfast** 2023-09-21 11:47 UTC
Labels: duplicate
