### ISSUE TITLE
Error while firing this command

### ISSUE THREAD

**Issue by omgaur7** [dotnet/upgrade-assistant#1509] opened 2023-08-04 10:15 UTC
getting this error while firing upgrade-assistant analyze command
![Capture](https://github.com/dotnet/upgrade-assistant/assets/141411302/093a35b3-f936-4b41-b2d6-2fb9b590c8f2)

**Comment by jstedfast** [comment] 2023-08-04 13:22
Starting with v0.5, the analyze command was removed.

Note: technically, it wasn't removed so much as the entire program was rewritten from scratch and the analyze command hasn't been implemented (yet?).

**Comment by jstedfast** [comment] 2023-09-21 11:45
This is a duplicate of issue https://github.com/dotnet/upgrade-assistant/issues/1491 and issue https://github.com/dotnet/upgrade-assistant/issues/1497

**Closed by jstedfast** 2023-09-21 11:45 UTC
