### ISSUE TITLE
Visual studio extension

### ISSUE THREAD

**Issue by vvijayalakshmi21** [dotnet/upgrade-assistant#311] opened 2021-03-04 04:12 UTC
Hi,
Is it in your roadmap to have upgrade assistant as an vs extension (similar to .net portability analyzer with an option to choose the required target .net core version)?

**Comment by sunandabalu** [comment] 2021-03-04 23:49
Thanks @vvijayalakshmi21. We do have in our backlog to explore the option of a VS integration.

**Comment by brandonh-msft** [comment] 2022-07-19 23:07
dupe of #54

**Closed by brandonh-msft** 2022-07-19 23:07 UTC
Labels: enhancement, community reported, Triaged, User Story
