### ISSUE TITLE
upgrade-assistant:  Unknown command 'analyze'

### ISSUE THREAD

**Issue by vanillabrian** [dotnet/upgrade-assistant#1517] opened 2023-09-09 11:36 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

The instructions say to run the command: 

> upgrade-assistant analyze <Path to csproj or sln to upgrade>

I got the following error:

> Error: Unknown command 'analyze'.
> 
>        analyze ViewModels.csproj
>        ^^^^^^^ No such command
>

**Comment by sc231997** [comment] 2023-09-21 08:32
Facing same issue :(

**Comment by jstedfast** [comment] 2023-09-21 11:43
This is a duplicate of issue #1491 and issue #1497

**Closed** 2023-09-21 11:43 UTC
Labels: duplicate
