### ISSUE TITLE
Support Packages.props

### ISSUE THREAD

**Issue by MikeAndrews90** [dotnet/upgrade-assistant#303] opened 2021-03-03 09:38 UTC
Our package references look like this, with no version numbers:

```
<PackageReference Include="FluentValidation" />
<PackageReference Include="Microsoft.CSharp" />
<PackageReference Include="System.ComponentModel.Annotations" />
<PackageReference Include="System.Security.Cryptography.Algorithms" />
<PackageReference Include="System.Security.Cryptography.X509Certificates" />
```
This is because we use a Packages.props file to maintain the package reference versions in one place for the whole solution.  See https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-packages.

However, the upgrade tool interprets these references as being invalid, and the NuGet upgrade moves them all to using a version, sometimes referencing entirely the wrong version of a package.

This is after the tool was run:

```
<PackageReference Include="FluentValidation" Version="6.4.1" />
<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
<PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
<PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
<PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
```

**Comment by sunandabalu** [comment] 2021-03-03 17:21
This is tracked here - https://github.com/dotnet/upgrade-assistant/issues/252 - yes currently upgrade-assistant does not support the use of central package version management, it will be something we can def look into. Closing this as duplicate of #252 .

**Closed by sunandabalu** 2021-03-03 17:21 UTC
Labels: community reported, enhancement
