### ISSUE TITLE
[Failed] Apply fix for UA0005: Do not use HttpContext.Current

### ISSUE THREAD

**Issue by georgikoemdzhiev** [dotnet/upgrade-assistant#918] opened 2021-11-08 14:43 UTC
- [x ] Include the log file `upgrade-assistant.clef` that is produced in the working directory
please see `upgrade-assistant.log` file attached bellow

### Describe the bug
When running the `upgrade` command there was an `Unexpected error applying step` being thrown 

### Exceptions (if any)
```
[14:22:58 INF] Applying upgrade step Apply fix for UA0005: Do not use HttpContext.Current
[14:22:58 ERR] Unexpected error applying step
System.ArgumentNullException: Value cannot be null. (Parameter 'document')
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.TryFixDiagnosticAsync(Diagnostic diagnostic, Document document, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.Steps.Source.CodeFixerStep.ApplyImplAsync(IUpgradeContext context, CancellationToken token)
   at Microsoft.DotNet.UpgradeAssistant.UpgradeStep.ApplyAsync(IUpgradeContext context, CancellationToken token) in /_/src/common/Microsoft.DotNet.UpgradeAssistant.Abstractions/UpgradeStep.cs:line 178
```

### Further technical details
- Windows version and bitness info (32-bit or 64-bit)
Windows 10 enterprise, 10.0.19042, 64 bit

- Include the output of `dotnet --list-sdks`
2.1.802 [C:\Program Files\dotnet\sdk]
2.2.300 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
3.1.108 [C:\Program Files\dotnet\sdk]
5.0.402 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`
0.3.252501+d008dcd65150d4d24cdeb8378cc517cc5b121b2

### File attachments
[upgrade-assistant.log](https://github.com/dotnet/upgrade-assistant/files/7497808/upgrade-assistant.log)

**Comment by k8e** [comment] 2022-01-14 01:31
Bump. Same issue.

**Comment by Thwar** [comment] 2022-07-01 13:59
Bump. Same. Trying to use the HttpContextHelper.cs class to access the HttpContext in both .NET Framework and .NET Standard.


`using System;
using System.Diagnostics;

#if NET || NETCOREAPP
using Microsoft.AspNetCore.Http;
#else
using System.Web;
#endif

namespace ReferralRock.MiddleTier
{
    /// <summary>
    /// Temporary helper class for retrieving the current <see cref="HttpContext"/> . This temporary
    /// workaround should be removed in the future and <see cref="HttpContext"/> should be retrieved
    /// from the current controller, middleware, or page instead.
#if NET || NETCOREAPP
    ///
    /// If working in another component, the current <see cref="HttpContext"/> can be retrieved from an <see cref="IHttpContextAccessor"/>
    /// retrieved via dependency injection.
#endif
    /// </summary>
    internal static class HttpContextHelper
    {
        private const string Message = "Prefer accessing HttpContext via injection";

        /// <summary>
        /// Gets the current <see cref="HttpContext"/>. Returns <c>null</c> if there is no current <see cref="HttpContext"/>.
        /// </summary>
#if NET || NETCOREAPP
#if NET5_0_OR_GREATER
        [Obsolete(Message, error: false, DiagnosticId = "HttpContextCurrent", UrlFormat = "https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context")]
#else
        [Obsolete(Message, error: false)]
#endif
        public static HttpContext Current => HttpContextAccessor.HttpContext;

        private static readonly HttpContextAccessor HttpContextAccessor = new HttpContextAccessor();
#else
#pragma warning disable UA0005 // Do not use HttpContext.Current
        [Obsolete(Message, error: false)]
        public static HttpContext Current => HttpContext.Current;
#pragma warning restore UA0005 // Do not use HttpContext.Current
#endif
    }
}
`

**Comment by brandonh-msft** [comment] 2022-08-24 00:10
I am unable to reproduce after the following:
1. Create blank .NET Framework 4.7.2 project
2. Add new Debug config w/ `NETCOREAPP` symbol
3. Add references to System.Web and the Microsoft.AspNetCore.Http nupkg

I ran UA `analyze` and got the following output:
```
Microsoft.DotNet.UpgradeAssistant.Cli.exe analyze .\ClassLibrary1.sln
-----------------------------------------------------------------------------------------------------------------
Microsoft .NET Upgrade Assistant v0.4.0-dev

We are interested in your feedback! Please use the following link to open a survey: https://aka.ms/DotNetUASurvey
-----------------------------------------------------------------------------------------------------------------

[16:58:05 INF] Loaded 8 extensions
[16:58:15 INF] Using MSBuild from C:\Program Files\dotnet\sdk\6.0.400\
[16:58:15 INF] Using Visual Studio install from C:\Program Files\Microsoft Visual Studio\2022\PubPreview [v17]
[16:58:24 INF] Writing output to C:\s\scratch\ClassLibrary1\AnalysisReport.sarif
[16:58:24 INF] Recommending executable TFM net6.0 because the project builds to a web app
[16:58:24 INF] Marking assembly reference System.Web for removal based on package mapping configuration ASP.NET
[16:58:24 INF] Adding framework reference Microsoft.AspNetCore.App based on package mapping configuration ASP.NET
[16:58:25 INF] Reference to .NET Upgrade Assistant analyzer package (Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, version 0.4.336902) needs to be added
[16:58:26 INF] Running analyzers on ClassLibrary1
[16:58:27 INF] Identified 1 diagnostics in project ClassLibrary1
[16:58:27 INF] Diagnostic UA0005 with the message HttpContext does not have a Current property; get the context from a controller or use HttpContextAccessor instead. generated
[16:58:27 INF] Analysis Complete, the report is available at C:\s\scratch\ClassLibrary1\AnalysisReport.sarif
```

I then ran UA `upgrade` which passed w/o issue:
<details><summary>output</summary>

```
Microsoft.DotNet.UpgradeAssistant.Cli.exe upgrade .\ClassLibrary1.sln --non-interactive
-----------------------------------------------------------------------------------------------------------------
Microsoft .NET Upgrade Assistant v0.4.0-dev

We are interested in your feedback! Please use the following link to open a survey: https://aka.ms/DotNetUASurvey
-----------------------------------------------------------------------------------------------------------------

[17:02:26 INF] Loaded 8 extensions
[17:02:28 INF] Using MSBuild from C:\Program Files\dotnet\sdk\6.0.400\
[17:02:28 INF] Using Visual Studio install from C:\Program Files\Microsoft Visual Studio\2022\PubPreview [v17]
[17:02:30 INF] Loading upgrade progress file at C:\s\scratch\ClassLibrary1\.upgrade-assistant
[17:02:31 INF] Initializing upgrade step Back up project

[17:02:31 INF] Applying upgrade step Back up project
[17:02:31 INF] Backing up C:\s\scratch\ClassLibrary1\ClassLibrary1 to C:\s\scratch\ClassLibrary1.backup\ClassLibrary1
[17:02:31 INF] Project backed up to C:\s\scratch\ClassLibrary1.backup\ClassLibrary1
[17:02:31 INF] Upgrade step Back up project applied successfully
[17:02:31 INF] Initializing upgrade step Convert project file to SDK style

[17:02:31 INF] Applying upgrade step Convert project file to SDK style
[17:02:31 INF] Converting project file format with try-convert, version 0.4.0-dev
[17:02:31 INF] Recommending executable TFM net6.0 because the project builds to a web app
C:\s\scratch\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj contains a reference to System.Web, which is not supported on .NET Core. You may have significant work ahead of you to fully port this project.
[17:02:34 INF] Converting project C:\s\scratch\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj to SDK style
[17:02:37 INF] Project file converted successfully! The project may require additional changes to build successfully against the new .NET target.
[17:02:39 INF] Upgrade step Convert project file to SDK style applied successfully
[17:02:40 INF] Initializing upgrade step Clean up NuGet package references
[17:02:40 INF] Initializing upgrade step Duplicate reference analyzer
[17:02:40 INF] Marking package System.ComponentModel.Annotations, Version=4.5.0 for removal because it is referenced elsewhere in the project with a higher version
[17:02:41 INF] Initializing upgrade step Remove package 'System.ComponentModel.Annotations'

[17:02:41 INF] Applying upgrade step Remove package 'System.ComponentModel.Annotations'
[17:02:41 INF] Removing outdated package reference: System.ComponentModel.Annotations, Version=4.5.0
[17:02:41 INF] Upgrade step Remove package 'System.ComponentModel.Annotations' applied successfully
[17:02:41 INF] Applying upgrade step Duplicate reference analyzer
[17:02:41 INF] Upgrade step Duplicate reference analyzer applied successfully
[17:02:41 INF] Initializing upgrade step Package map reference analyzer
[17:02:41 INF] No package updates needed
[17:02:41 INF] Initializing upgrade step Target compatibility reference analyzer
[17:02:41 INF] No package updates needed
[17:02:41 INF] Initializing upgrade step Upgrade assistant reference analyzer
[17:02:42 INF] Reference to .NET Upgrade Assistant analyzer package (Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, version 0.4.336902) needs to be added
[17:02:42 INF] Initializing upgrade step Add package 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers'

[17:02:42 INF] Applying upgrade step Add package 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers'
[17:02:42 INF] Adding package reference: Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, Version=0.4.336902
[17:02:42 INF] Upgrade step Add package 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers' applied successfully
[17:02:42 INF] Applying upgrade step Upgrade assistant reference analyzer
[17:02:42 INF] Upgrade step Upgrade assistant reference analyzer applied successfully
[17:02:43 INF] Initializing upgrade step Windows Compatibility Pack Analyzer
[17:02:43 INF] No package updates needed
[17:02:43 INF] Initializing upgrade step MyDotAnalyzer reference analyzer
[17:02:43 INF] No package updates needed
[17:02:43 INF] Initializing upgrade step Newtonsoft.Json reference analyzer
[17:02:43 INF] No package updates needed
[17:02:43 INF] Initializing upgrade step Windows App SDK package analysis
[17:02:43 INF] No package updates needed
[17:02:43 INF] Initializing upgrade step Transitive reference analyzer
[17:02:43 INF] Initializing upgrade step Remove package 'Microsoft.AspNetCore.Http.Abstractions'

[17:02:43 INF] Applying upgrade step Remove package 'Microsoft.AspNetCore.Http.Abstractions'
[17:02:43 INF] Removing outdated package reference: Microsoft.AspNetCore.Http.Abstractions, Version=2.2.0
[17:02:43 INF] Upgrade step Remove package 'Microsoft.AspNetCore.Http.Abstractions' applied successfully
[17:02:43 INF] Initializing upgrade step Remove package 'Microsoft.AspNetCore.Http.Features'

[17:02:43 INF] Applying upgrade step Remove package 'Microsoft.AspNetCore.Http.Features'
[17:02:43 INF] Removing outdated package reference: Microsoft.AspNetCore.Http.Features, Version=2.2.0
[17:02:43 INF] Upgrade step Remove package 'Microsoft.AspNetCore.Http.Features' applied successfully
[17:02:43 INF] Initializing upgrade step Remove package 'Microsoft.AspNetCore.WebUtilities'

[17:02:43 INF] Applying upgrade step Remove package 'Microsoft.AspNetCore.WebUtilities'
[17:02:43 INF] Removing outdated package reference: Microsoft.AspNetCore.WebUtilities, Version=2.2.0
[17:02:43 INF] Upgrade step Remove package 'Microsoft.AspNetCore.WebUtilities' applied successfully
[17:02:43 INF] Initializing upgrade step Remove package 'Microsoft.Extensions.DependencyInjection.Abstractions'

[17:02:43 INF] Applying upgrade step Remove package 'Microsoft.Extensions.DependencyInjection.Abstractions'
[17:02:43 INF] Removing outdated package reference: Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0
[17:02:43 INF] Upgrade step Remove package 'Microsoft.Extensions.DependencyInjection.Abstractions' applied successfully
[17:02:43 INF] Initializing upgrade step Remove package 'Microsoft.Extensions.ObjectPool'

[17:02:43 INF] Applying upgrade step Remove package 'Microsoft.Extensions.ObjectPool'
[17:02:43 INF] Removing outdated package reference: Microsoft.Extensions.ObjectPool, Version=2.2.0
[17:02:43 INF] Upgrade step Remove package 'Microsoft.Extensions.ObjectPool' applied successfully
[17:02:43 INF] Initializing upgrade step Remove package 'Microsoft.Extensions.Options'

[17:02:43 INF] Applying upgrade step Remove package 'Microsoft.Extensions.Options'
[17:02:43 INF] Removing outdated package reference: Microsoft.Extensions.Options, Version=2.2.0
[17:02:43 INF] Upgrade step Remove package 'Microsoft.Extensions.Options' applied successfully
[17:02:44 INF] Initializing upgrade step Remove package 'Microsoft.Extensions.Primitives'

[17:02:44 INF] Applying upgrade step Remove package 'Microsoft.Extensions.Primitives'
[17:02:44 INF] Removing outdated package reference: Microsoft.Extensions.Primitives, Version=2.2.0
[17:02:44 INF] Upgrade step Remove package 'Microsoft.Extensions.Primitives' applied successfully
[17:02:44 INF] Initializing upgrade step Remove package 'Microsoft.Net.Http.Headers'

[17:02:44 INF] Applying upgrade step Remove package 'Microsoft.Net.Http.Headers'
[17:02:44 INF] Removing outdated package reference: Microsoft.Net.Http.Headers, Version=2.2.0
[17:02:44 INF] Upgrade step Remove package 'Microsoft.Net.Http.Headers' applied successfully
[17:02:44 INF] Initializing upgrade step Remove package 'System.Buffers'

[17:02:44 INF] Applying upgrade step Remove package 'System.Buffers'
[17:02:44 INF] Removing outdated package reference: System.Buffers, Version=4.5.0
[17:02:44 INF] Upgrade step Remove package 'System.Buffers' applied successfully
[17:02:44 INF] Initializing upgrade step Remove package 'System.Memory'

[17:02:44 INF] Applying upgrade step Remove package 'System.Memory'
[17:02:44 INF] Removing outdated package reference: System.Memory, Version=4.5.1
[17:02:44 INF] Upgrade step Remove package 'System.Memory' applied successfully
[17:02:44 INF] Initializing upgrade step Remove package 'System.Numerics.Vectors'

[17:02:44 INF] Applying upgrade step Remove package 'System.Numerics.Vectors'
[17:02:44 INF] Removing outdated package reference: System.Numerics.Vectors, Version=4.4.0
[17:02:44 INF] Upgrade step Remove package 'System.Numerics.Vectors' applied successfully
[17:02:44 INF] Initializing upgrade step Remove package 'System.Runtime.CompilerServices.Unsafe'

[17:02:44 INF] Applying upgrade step Remove package 'System.Runtime.CompilerServices.Unsafe'
[17:02:44 INF] Removing outdated package reference: System.Runtime.CompilerServices.Unsafe, Version=4.5.1
[17:02:44 INF] Upgrade step Remove package 'System.Runtime.CompilerServices.Unsafe' applied successfully
[17:02:44 INF] Initializing upgrade step Remove package 'System.Text.Encodings.Web'

[17:02:44 INF] Applying upgrade step Remove package 'System.Text.Encodings.Web'
[17:02:44 INF] Removing outdated package reference: System.Text.Encodings.Web, Version=4.5.0
[17:02:44 INF] Upgrade step Remove package 'System.Text.Encodings.Web' applied successfully
[17:02:44 INF] Applying upgrade step Transitive reference analyzer
[17:02:44 INF] Upgrade step Transitive reference analyzer applied successfully
[17:02:44 INF] Applying upgrade step Clean up NuGet package references
[17:02:44 INF] Upgrade step Clean up NuGet package references applied successfully
[17:02:45 INF] Initializing upgrade step Update TFM
[17:02:45 INF] Recommending executable TFM net6.0 because the project builds to a web app
[17:02:45 INF] TFM needs updated to net6.0

[17:02:45 INF] Applying upgrade step Update TFM
[17:02:45 INF] Recommending executable TFM net6.0 because the project builds to a web app
[17:02:58 INF] Updated TFM to net6.0
[17:02:58 INF] Upgrade step Update TFM applied successfully
[17:02:59 INF] Initializing upgrade step Update NuGet Packages
[17:02:59 INF] Initializing upgrade step Duplicate reference analyzer
[17:02:59 INF] No package updates needed
[17:02:59 INF] Initializing upgrade step Package map reference analyzer
[17:02:59 INF] Marking assembly reference System.Web for removal based on package mapping configuration ASP.NET
[17:02:59 INF] Adding framework reference Microsoft.AspNetCore.App based on package mapping configuration ASP.NET
[17:02:59 INF] Initializing upgrade step Remove reference 'System.Web'

[17:02:59 INF] Applying upgrade step Remove reference 'System.Web'
[17:02:59 INF] Removing outdated assembly reference: System.Web
[17:02:59 INF] Upgrade step Remove reference 'System.Web' applied successfully
[17:02:59 INF] Initializing upgrade step Add framework reference 'Microsoft.AspNetCore.App'

[17:02:59 INF] Applying upgrade step Add framework reference 'Microsoft.AspNetCore.App'
[17:02:59 INF] Adding framework reference: Microsoft.AspNetCore.App
[17:02:59 INF] Upgrade step Add framework reference 'Microsoft.AspNetCore.App' applied successfully
[17:02:59 INF] Applying upgrade step Package map reference analyzer
[17:03:06 INF] Upgrade step Package map reference analyzer applied successfully
[17:03:06 INF] Initializing upgrade step Target compatibility reference analyzer
[17:03:06 INF] No package updates needed
[17:03:06 INF] Initializing upgrade step Upgrade assistant reference analyzer
[17:03:06 INF] No package updates needed
[17:03:06 INF] Initializing upgrade step Windows Compatibility Pack Analyzer
[17:03:06 INF] No package updates needed
[17:03:06 INF] Initializing upgrade step MyDotAnalyzer reference analyzer
[17:03:06 INF] No package updates needed
[17:03:06 INF] Initializing upgrade step Newtonsoft.Json reference analyzer
[17:03:06 INF] No package updates needed
[17:03:06 INF] Initializing upgrade step Windows App SDK package analysis
[17:03:07 INF] No package updates needed
[17:03:07 INF] Initializing upgrade step Transitive reference analyzer
[17:03:07 INF] No package updates needed
[17:03:07 INF] Applying upgrade step Update NuGet Packages
[17:03:07 INF] Upgrade step Update NuGet Packages applied successfully
[17:03:07 INF] Initializing upgrade step Add template files
[17:03:07 INF] 0 expected template items needed
[17:03:07 INF] Initializing upgrade step Upgrade app config files
[17:03:07 INF] Found 0 app settings for upgrade:
[17:03:07 INF] Found 0 connection strings for upgrade:
[17:03:07 INF] 0 web page namespace imports need upgraded:
[17:03:07 INF] Initializing upgrade step Update source code
[17:03:07 INF] Running analyzers on ClassLibrary1
[17:03:10 INF] Identified 0 diagnostics in project ClassLibrary1
[17:03:11 INF] Initializing upgrade step Move to next project

[17:03:11 INF] Applying upgrade step Move to next project
[17:03:11 INF] Upgrade step Move to next project applied successfully
[17:03:11 INF] Recommending executable TFM net6.0 because the project builds to a web app
[17:03:11 INF] Recommending executable TFM net6.0 because the project builds to a web app
[17:03:11 INF] Recommending executable TFM net6.0 because the project builds to a web app
[17:03:11 INF] Initializing upgrade step Finalize upgrade

[17:03:11 INF] Applying upgrade step Finalize upgrade
[17:03:11 INF] Upgrade step Finalize upgrade applied successfully
[17:03:11 INF] Upgrade has completed. Please review any changes.
[17:03:11 INF] Deleting upgrade progress file at C:\s\scratch\ClassLibrary1\.upgrade-assistant
```

</details>

If anybody can provide a csproj/sln that reproduces this issue, that would be great! Closing for now.

**Closed by brandonh-msft** 2022-08-24 00:10 UTC
Labels: bug, community reported, Triaged
