### ISSUE TITLE
Ran into problem when trying to install the upgrade assistant

### ISSUE THREAD

**Issue by odc19** [dotnet/upgrade-assistant#1293] opened 2022-09-12 08:57 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I'm using Windows 10.

I got this error:

> 
C:\Users\odancretu>dotnet tool install -g --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources upgrade-assistant
C:\Users\odancretu\AppData\Local\Temp\gvdivb3h.e3w\restore.csproj : warning NU1801: The local source 'C:\Users\odancretu\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\odancretu\AppData\Local\Temp\gvdivb3h.e3w\restore.csproj : warning NU1801: Failed to retrieve information about 'upgrade-assistant' from remote source 'https://api.nuget.org/v3-flatcontainer/upgrade-assistant/index.json'.
C:\Users\odancretu\AppData\Local\Temp\gvdivb3h.e3w\restore.csproj : warning NU1801: Failed to retrieve information about 'upgrade-assistant' from remote source 'https://api.nuget.org/v3-flatcontainer/upgrade-assistant/index.json'.
C:\Users\odancretu\AppData\Local\Temp\gvdivb3h.e3w\restore.csproj : warning NU1801: The local source 'C:\Users\odancretu\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\odancretu\AppData\Local\Temp\gvdivb3h.e3w\restore.csproj : warning NU1801: Failed to retrieve information about 'upgrade-assistant' from remote source 'https://api.nuget.org/v3-flatcontainer/upgrade-assistant/index.json'.
C:\Users\odancretu\AppData\Local\Temp\gvdivb3h.e3w\restore.csproj : warning NU1801: The local source 'C:\Users\odancretu\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\odancretu\AppData\Local\Temp\gvdivb3h.e3w\restore.csproj : error NU1101: Unable to find package upgrade-assistant. No packages exist with this id in source(s): C:\Users\odancretu\'https:\api.nuget.org\v3\index.json', nuget
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
> 

when running the following command:

`dotnet tool install -g --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources upgrade-assistant`

**Comment by brandonh-msft** [comment] 2022-09-21 20:02
@odc19 I'm unable to reproduce this - what shell/terminal/command line program are you using? It appears to be misinterpreting the `'` characters around the nuget source URL. Perhaps try using `"` or omitting them altogether and see if that works?

**Comment by MarvusMedia** [comment] 2022-09-26 20:38
Replacing single quotes (') with double quotes (") fixed it for me. Thanks.

**Comment by brandonh-msft** [comment] 2022-09-26 21:01
Thanks we'll work on updating the docs

**Comment by cathysull** [comment] 2022-10-07 19:08
The change to update the quotes in the tutorial just got merged in so this has been addressed! Thanks @odc19 for reporting this issue!

https://github.com/dotnet/website/pull/4384

**Closed by cathysull** 2022-10-07 19:08 UTC
Labels: documentation, good first issue, community reported, Triaged, ToolFailedToInstall
