### ISSUE TITLE
Test projects not supported

### ISSUE THREAD

**Issue by brandonh-msft** [dotnet/upgrade-assistant#1193] opened 2022-06-27 15:56 UTC
Test project types (GUID `3AC096D0-A1C2-E12C-1390-A8335801FDAB`) are unsupported by the tool and should at least be converted to SDK style:

Errmsg: 
```
Tests.csproj is an unsupported project type. Not all project type guids are supported.
All supported project type guids:
        f184b08f-c81c-45f6-a57f-5abd9991f28f
        fae04ec0-301f-11d3-bf4b-00c04f79efbc
        60dc8134-eba5-43b8-bcc9-bb4bc16c2548
All given project type guids:
        {3AC096D0-A1C2-E12C-1390-A8335801FDAB}
        {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}
```

**Comment by brandonh-msft** [comment] 2022-06-27 16:10
Looks like a dupe of https://github.com/dotnet/try-convert/issues/421
which also looks to be a regression of https://github.com/dotnet/try-convert/issues/156

@jmarolf

**Comment by sunandabalu** [comment] 2022-06-27 16:56
Dupe of https://github.com/dotnet/upgrade-assistant/issues/997

**Closed by sunandabalu** 2022-06-27 16:56 UTC
Labels: enhancement, community reported
